package uaspbo;

import java.sql.*;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.JOptionPane;
public class LoginFrame extends javax.swing.JFrame {

    /**
     * Creates new form LoginFrame
     */
    public LoginFrame() {
        initComponents();
        Connect();
        this.setResizable(false);//fixed size
        
    }

    Connection con;
    PreparedStatement pst;
    ResultSet rs;
    
    public void Connect(){
        try { 
            Class.forName("com.mysql.jdbc.Driver");
            con = DriverManager.getConnection("jdbc:mysql://localhost/dbmahasiswa", "root", "");
        } catch (ClassNotFoundException ex) {
            Logger.getLogger(RegisJFrame.class.getName()).log(Level.SEVERE, null, ex);
        } catch(SQLException ex) {
            Logger.getLogger(RegisJFrame.class.getName()).log(Level.SEVERE, null, ex);
        }
    }
    
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel3 = new javax.swing.JPanel();
        jPanel4 = new javax.swing.JPanel();
        jPanel1 = new javax.swing.JPanel();
        Plogo = new javax.swing.JPanel();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        Plogin = new javax.swing.JPanel();
        txtusername = new javax.swing.JTextField();
        txtpassword = new javax.swing.JPasswordField();
        jSeparator1 = new javax.swing.JSeparator();
        jSeparator2 = new javax.swing.JSeparator();
        jSeparator3 = new javax.swing.JSeparator();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        btnsignin = new javax.swing.JButton();
        jLabel3 = new javax.swing.JLabel();
        btntosignup = new javax.swing.JButton();

        javax.swing.GroupLayout jPanel3Layout = new javax.swing.GroupLayout(jPanel3);
        jPanel3.setLayout(jPanel3Layout);
        jPanel3Layout.setHorizontalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 100, Short.MAX_VALUE)
        );
        jPanel3Layout.setVerticalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 100, Short.MAX_VALUE)
        );

        javax.swing.GroupLayout jPanel4Layout = new javax.swing.GroupLayout(jPanel4);
        jPanel4.setLayout(jPanel4Layout);
        jPanel4Layout.setHorizontalGroup(
            jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 100, Short.MAX_VALUE)
        );
        jPanel4Layout.setVerticalGroup(
            jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 100, Short.MAX_VALUE)
        );

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jPanel1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        Plogo.setBackground(new java.awt.Color(102, 102, 102));

        jLabel4.setIcon(new javax.swing.ImageIcon(getClass().getResource("/uaspbo/icons8-student-90.png"))); // NOI18N

        jLabel5.setFont(new java.awt.Font("Prompt Semibold", 0, 24)); // NOI18N
        jLabel5.setForeground(new java.awt.Color(255, 255, 255));
        jLabel5.setText("Welcome, Student");

        javax.swing.GroupLayout PlogoLayout = new javax.swing.GroupLayout(Plogo);
        Plogo.setLayout(PlogoLayout);
        PlogoLayout.setHorizontalGroup(
            PlogoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(PlogoLayout.createSequentialGroup()
                .addGroup(PlogoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(PlogoLayout.createSequentialGroup()
                        .addGap(48, 48, 48)
                        .addComponent(jLabel5))
                    .addGroup(PlogoLayout.createSequentialGroup()
                        .addGap(110, 110, 110)
                        .addComponent(jLabel4)))
                .addContainerGap(48, Short.MAX_VALUE))
        );
        PlogoLayout.setVerticalGroup(
            PlogoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(PlogoLayout.createSequentialGroup()
                .addGap(126, 126, 126)
                .addComponent(jLabel4, javax.swing.GroupLayout.PREFERRED_SIZE, 90, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jLabel5)
                .addContainerGap(192, Short.MAX_VALUE))
        );

        jPanel1.add(Plogo, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, -1, -1));

        Plogin.setBackground(new java.awt.Color(255, 255, 255));
        Plogin.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        txtusername.setFont(new java.awt.Font("Poppins Medium", 0, 18)); // NOI18N
        txtusername.setForeground(new java.awt.Color(51, 51, 51));
        txtusername.setText("Usename");
        txtusername.setBorder(null);
        Plogin.add(txtusername, new org.netbeans.lib.awtextra.AbsoluteConstraints(80, 140, 270, -1));

        txtpassword.setFont(new java.awt.Font("Prompt Medium", 0, 18)); // NOI18N
        txtpassword.setForeground(new java.awt.Color(51, 51, 51));
        txtpassword.setText("jPasswordField1");
        txtpassword.setBorder(null);
        Plogin.add(txtpassword, new org.netbeans.lib.awtextra.AbsoluteConstraints(80, 200, 270, -1));

        jSeparator1.setForeground(new java.awt.Color(102, 102, 102));
        jSeparator1.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        Plogin.add(jSeparator1, new org.netbeans.lib.awtextra.AbsoluteConstraints(80, 170, 270, 20));
        Plogin.add(jSeparator2, new org.netbeans.lib.awtextra.AbsoluteConstraints(80, 170, 270, -1));

        jSeparator3.setForeground(new java.awt.Color(102, 102, 102));
        Plogin.add(jSeparator3, new org.netbeans.lib.awtextra.AbsoluteConstraints(80, 230, 270, 30));

        jLabel1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/uaspbo/icons8-password-20.png"))); // NOI18N
        Plogin.add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 200, -1, 30));

        jLabel2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/uaspbo/icons8-user-20.png"))); // NOI18N
        Plogin.add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 140, -1, 30));

        btnsignin.setFont(new java.awt.Font("Poppins SemiBold", 0, 20)); // NOI18N
        btnsignin.setText("Sign In");
        btnsignin.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnsigninActionPerformed(evt);
            }
        });
        Plogin.add(btnsignin, new org.netbeans.lib.awtextra.AbsoluteConstraints(150, 260, -1, -1));

        jLabel3.setFont(new java.awt.Font("Poppins Medium", 0, 12)); // NOI18N
        jLabel3.setText("Don't have an account ?");
        Plogin.add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(90, 420, -1, -1));

        btntosignup.setFont(new java.awt.Font("Poppins Medium", 0, 12)); // NOI18N
        btntosignup.setForeground(new java.awt.Color(153, 153, 255));
        btntosignup.setText("Sign Up");
        btntosignup.setBorder(null);
        btntosignup.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btntosignupActionPerformed(evt);
            }
        });
        Plogin.add(btntosignup, new org.netbeans.lib.awtextra.AbsoluteConstraints(240, 420, -1, -1));

        jPanel1.add(Plogin, new org.netbeans.lib.awtextra.AbsoluteConstraints(313, 0, 394, 452));

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void btntosignupActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btntosignupActionPerformed
        this.hide();
        RegisJFrame regisf = new RegisJFrame();
        regisf.show();
    }//GEN-LAST:event_btntosignupActionPerformed

    private void btnsigninActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnsigninActionPerformed
        String user = txtusername.getText();
        String pass = new String(txtpassword.getPassword());
        try {
            pst = con.prepareStatement("SELECT * FROM tbakun");
            rs = pst.executeQuery();
            
            while(rs.next()) {
                String uname = rs.getString(("nim"));
                String pw = rs.getString("password");
                String state = rs.getString("status");
                
                if((user.equals(uname)) && (pass.equals(pw )) && ("Mahasiswa".equals(state))) {
                    new DosenFrame().setVisible(true);
                    this.hide();
                }else if((user.equals(uname)) && (pass.equals(pw )) && ("Dosen".equals(state))){
                    new MahasiswaFrame().setVisible(true);
                    this.hide();
                }
            }
        } catch (SQLException ex) {
            Logger.getLogger(LoginFrame.class.getName()).log(Level.SEVERE, null, ex);
        }
    }//GEN-LAST:event_btnsigninActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(LoginFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(LoginFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(LoginFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(LoginFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new LoginFrame().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JPanel Plogin;
    private javax.swing.JPanel Plogo;
    private javax.swing.JButton btnsignin;
    private javax.swing.JButton btntosignup;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JPanel jPanel4;
    private javax.swing.JSeparator jSeparator1;
    private javax.swing.JSeparator jSeparator2;
    private javax.swing.JSeparator jSeparator3;
    private javax.swing.JPasswordField txtpassword;
    private javax.swing.JTextField txtusername;
    // End of variables declaration//GEN-END:variables
}
